// 02.react/2.react脚手架/src/pages/List/index.jsx
import React, { Component } from "react";
import PubSub from "pubsub-js";
import axios from "axios";

import "./index.css";

export default class List extends Component {
  state = {
    isFirstView: true, // 代表是否是初始化显示
    isLoading: false, // 代表是否请求中
    users: null, // 代表请求成功的数据
    error: null, // 代表请求失败的原因
  };

  componentDidMount() {
    PubSub.subscribe("SEARCHNAME", (msg, searchName) => {
      // 发送请求之前切换成loading
      this.setState({
        isFirstView: false,
        isLoading: true,
      });
      // 发送请求  https://api.github.com/search/users
      /*
        用代理服务器解决跨域：
          1. 配置 webpack.config.js  devServer proxy (和Vue基本一致)
          2. 页面中需要访问代理服务器。代理服务器会将请求转发到目标服务器
      */
      axios
        .get("http://localhost:9527/api/search/users", {
          params: {
            q: searchName,
          },
        })
        .then((response) => {
          console.log("请求成功", response);
          this.setState({
            users: response.data.items.map((user) => {
              return {
                login: user.login,
                avatar_url: user.avatar_url,
                html_url: user.html_url,
                id: user.id,
              };
            }),
            isLoading: false,
          });
        })
        .catch((err) => {
          console.log("请求失败", err);
          this.setState({
            users: null,
            error: "网络出现问题，请刷新试试~",
            isLoading: false,
          });
        });
    });
  }

  componentWillUnmount() {
    PubSub.unsubscribe("SEARCHNAME");
  }

  render() {
    const { isFirstView, isLoading, users, error } = this.state;

    if (isFirstView) {
      return <h1>Enter Name To Search</h1>;
    }

    if (isLoading) {
      return <h1>Loading...</h1>;
    }

    if (users) {
      return (
        <div className="row">
          {users.map((user) => {
            return (
              <div className="card" key={user.id}>
                <a href={user.html_url} target="_blank">
                  <img src={user.avatar_url} style={{ width: 100 }} />
                </a>
                <p className="card-text">{user.login}</p>
              </div>
            );
          })}
        </div>
      );
    }

    return <h1>{error}</h1>;
  }
}

// 03.VueComponent/07.ajax/src/components/List.vue
<template>
  <!-- 必须有根标签 -->
  <div>
    <p v-if="isFirstView">请输入搜索内容</p>
    <p v-else-if="isLoading">Loading...</p>
    <div class="row" v-else-if="users">
      <div class="card" v-for="(user, index) in users" :key="index">
        <a :href="user.html_url" target="_blank">
          <img :src="user.avatar_url" style="width: 100px" />
        </a>
        <p class="card-text">{{ user.login }}</p>
      </div>
    </div>
    <p v-else>{{ errorMsg }}</p>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      isFirstView: true, // 决定是否初始化显示
      isLoading: false, // 决定是否在请求中
      users: null, // 决定请求成功的数据
      errorMsg: "", // 决定请求失败的信息
    };
  },
  created() {
    // 绑定事件
    this.$bus.$on("search-name", this.reqUsersData);
  },
  methods: {
    async reqUsersData(searchName) {
      // 请求之前，切换data
      this.isFirstView = false;
      this.isLoading = true;

      /*
        请求失败怎么捕获async函数的错误？ 
        try{
          // 防止可能出错代码（异步代码）
        } catch(e) {
          // 一旦try里面出错了，后面代码（try出错代码的后面代码）就不会执行了
          // 会直接执行catch中代码
          // 处理try的异常
        }
      */

      try {
        // 发送请求
        const response = await axios.get(
          // `http://localhost:9527/api/search/users?q=${searchName}`
          `/api/search/users?q=${searchName}`
        );

        // 只想保留三个数据：login/html_url/avatar_url
        // 长度不变值变 --> map
        // 对数据进行处理
        const users = response.data.items.map((user) => {
          return {
            login: user.login,
            html_url: user.html_url,
            avatar_url: user.avatar_url,
          };
        });

        // 更新data
        this.users = users;
        this.isLoading = false;
      } catch (e) {
        console.log(e);

        // 更新data
        this.isLoading = false;
        this.errorMsg = "网络出现故障，请刷新试试~";
      }
    },
  },
};
</script>

<style scoped>
.card {
  float: left;
  width: 33.333%;
  padding: 0.75rem;
  margin-bottom: 2rem;
  border: 1px solid #efefef;
  text-align: center;
}

.card > img {
  margin-bottom: 0.75rem;
  border-radius: 100px;
}

.card-text {
  font-size: 85%;
}
</style>
