// 03.VueComponent/08.vuex/src-vuex/App.vue
<template>
  <div>
    <p>
      clicked: {{ this.$store.state.count }} times, count is {{ oddOrEven }}
    </p>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementIfOdd">increment if odd</button>
    <button @click="incrementAsync">increment async</button>
  </div>
</template>

<script>
export default {
  mounted() {
    /*
      更新数据和读取数据的方法都在store中
        读取数据 this.$store.state.xxx
        更新数据 
          触发actions this.$store.dispatch('xxx')
          触发mutaions this.$store.commit('xxx')
    */
    // console.log(this.$store);
  },
  computed: {
    oddOrEven() {
      return this.$store.state.count % 2 === 1 ? "奇数" : "偶数";
    },
  },
  methods: {
    increment() {
      // 触发actions --> increment action函数的调用
      this.$store.dispatch("increment");
    },
    decrement() {
      this.$store.dispatch("decrement");
    },
    incrementIfOdd() {
      this.$store.dispatch("incrementIfOdd");
    },
    incrementAsync() {
      this.$store.dispatch("incrementAsync");
    },
  },
};
</script>

<style></style>

// 02.react/5.my_react/src/App.jsx
import React, { Component } from "react";

import store from "./redux/store";
import { increment, decrement } from "./redux/actions";

export default class App extends Component {
  state = {
    number: 1,
  };

  handleChange = (e) => {
    this.setState({
      // 收集数据是字符串，转换为number
      number: +e.target.value,
    });
  };

  increment = () => {
    const { number } = this.state;
    // 调用actions生成action对象
    const action = increment(number);
    // 调用dispatch方法触发reducers函数，从而更新store状态数据
    store.dispatch(action);
  };

  decrement = () => {
    const { number } = this.state;
    store.dispatch(decrement(number));
  };

  incrementIfOdd = () => {
    const count = store.getState();
    // 如果是奇数就加
    if (count & 1) {
      const { number } = this.state;
      store.dispatch(increment(number));
    }
  };

  incrementAsync = () => {
    setTimeout(() => {
      const { number } = this.state;
      store.dispatch(increment(number));
    }, 1000);
  };

  render() {
    // 读取状态，展示
    const count = store.getState();

    return (
      <>
        <p>click {count} times</p>
        <select onChange={this.handleChange}>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>
        <button onClick={this.increment}>+</button>
        <button onClick={this.decrement}>-</button>
        <button onClick={this.incrementIfOdd}>increment if odd</button>
        <button onClick={this.incrementAsync}>increment async</button>
      </>
    );
  }
}
