// 02.react/4.react_cli/src/App.jsx
import React, { Component } from "react";

import Add from "./pages/Add";
import List from "./pages/List";

export default class App extends Component {
  render() {
    return (
      <div>
        <header className="site-header jumbotron">
          <div className="container">
            <div className="row">
              <div className="col-xs-12">
                <h1>请发表对React的评论</h1>
              </div>
            </div>
          </div>
        </header>
        <div className="container">
          <Add />
          <List />
        </div>
      </div>
    );
  }
}

// 03.VueComponent/04.Comment/src-全局事件总线/App.vue
<template>
  <div>
    <header class="site-header jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1>请发表对Vue的评论</h1>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <AddComment />
      <CommentList />
    </div>
  </div>
</template>

<script>
// 1. 引入组件
import AddComment from "@comps/AddComment";
import CommentList from "@comps/CommentList";

export default {
  components: {
    // 2. 注册组件
    AddComment,
    CommentList,
  },
};
</script>

<style></style>
