// 03.VueComponent/07.ajax/src/components/Search.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchName"
      />
      <button @click="search">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      searchName: "",
    };
  },
  methods: {
    search() {
      // 收集数据
      const searchName = this.searchName.trim();
      // 触发事件
      this.$bus.$emit("search-name", searchName);
    },
  },
};
</script>

<style scoped></style>

// 02.react/2.react脚手架/src-hooks练习/pages/Search/index.jsx
import React, { useState } from "react";
import PubSub from "pubsub-js";

export default function Search() {
  // 定义state
  const [searchName, setSearchName] = useState("");

  const handleChange = (e) => {
    setSearchName(e.target.value.trim());
  };

  const handleClick = () => {
    // 将数据发送给List组件
    if (searchName) {
      PubSub.publish("SEARCHNAME", searchName);
    }
  };

  return (
    <section className="jumbotron">
      <h3 className="jumbotron-heading">Search Github Users</h3>
      <div>
        <input
          type="text"
          placeholder="enter the name you search"
          onChange={handleChange}
        />
        <button onClick={handleClick}>Search</button>
      </div>
    </section>
  );
}
