// 03.VueComponent/09.router/src/pages/Home.vue
<template>
  <div>
    <h1>Home组件</h1>
    <ul class="nav nav-tabs">
      <li>
        <router-link to="/home/news">News</router-link>
      </li>
      <li>
        <router-link to="/home/message">Message</router-link>
      </li>
    </ul>
    <!-- 显示当前路由组件 -->
    <router-view></router-view>
  </div>
</template>

<script>
export default {};
</script>

<style></style>

// 02.react/2.react脚手架/src-11-前端路由/pages/Home/index.jsx
import React, { Component } from "react";

import { NavLink, Route, Switch, Redirect } from "react-router-dom";

import News from "../News";
import Messages from "../Messages";

export default class Home extends Component {
  render() {
    return (
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className="nav nav-tabs">
            <li>
              <NavLink className="list-group-item" to="/home/news">
                News
              </NavLink>
            </li>
            <li>
              <NavLink className="list-group-item" to="/home/message">
                Message
              </NavLink>
            </li>
          </ul>
          <Switch>
            <Route path="/home/message" component={Messages} />
            <Route path="/home/news" component={News} />
            <Redirect to="/home/news" />
          </Switch>
        </div>
      </div>
    );
  }
}
