// 03.VueComponent/09.router/src/App.vue
<template>
  <div>
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="page-header">
          <h2>Vue Router Demo</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 
            vueRouter 除了给实例对象添加属性，还添加了两个全局组件
              <router-link></router-link> 路由链接
                相当于a标签
                特点：不会发送请求，不会刷新页面，只会更新浏览器地址
                点击功能：
                  1. 改变浏览器地址
                  2. 给当前a标签添加一些类名：
                    .router-link-exact-active 
                    .router-link-active

              <router-view></router-view>
                显示当前路由组件
                当前路由组件是哪个？ 
                  路由配置中的path是否匹配上当前浏览器地址，
                  匹配上了，component就是当前路由组件
           -->
          <router-link class="list-group-item" to="/about">About</router-link>
          <router-link class="list-group-item" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 显示当前路由组件 -->
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
.router-link-active {
  color: red !important;
}
</style>

// 02.react/2.react脚手架/src/App.jsx
import React, { Component } from "react";

import {
  BrowserRouter,
  HashRouter,
  Link,
  NavLink,
  Route,
  Redirect,
  Switch,
} from "react-router-dom";

import About from "./pages/About";
import Home from "./pages/Home";

export default class App extends Component {
  render() {
    return (
      // 最外面必须使用Router，里面子组件才能使用router技术
      // 给里面子组件传递需要用的属性 history
      <HashRouter>
        <div className="row">
          <div className="col-xs-offset-2 col-xs-8">
            <div className="page-header">
              <h2>React Router Demo</h2>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
              {/* 
                Link组件：1. 添加浏览器历史记录
                NavLink组件：1. 添加浏览器历史记录 2. 选中时多一个类名 active
                
                什么时候用Link，什么时候用NavLink？
                  需要选中时有特殊样式时用NavLink
                  如果不需要就用Link
              */}
              <NavLink className="list-group-item" to="/about">
                About
              </NavLink>
              <Link className="list-group-item" to="/home">
                Home
              </Link>
            </div>
          </div>
          <div className="col-xs-6">
            <div className="panel">
              <div className="panel-body">
                {/* 
                  Switch 切换
                    能保证Route只有一个生效，只有一个会加载
                    默认情况下，从上到下依次匹配
                */}
                <Switch>
                  {/* 
                  Route负责根据浏览器历史记录的变化，一旦匹配上，就会加载当前组件 
                  如果之前加载过，没有匹配上，就会卸载
                  如果之前没有加载过。就不加载
                */}
                  <Route path="/about" component={About} />
                  <Route path="/home" component={Home} />
                  {/* 
                  Redirect组件会匹配所有地址，一旦匹配上就会自动更新浏览器历史记录
                */}
                  <Redirect to="/home" />
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </HashRouter>
    );
  }
}
